@startuml
!include ../.PlantUMLSequence.config
skinparam wrapWidth 0

title <size:30>View Manga:Add Required Columns to List Sequence Diagram

participant "MangaList" as ml <<class>>
participant "row number" as row
participant "manga name" as name
participant "deadline" as dl
participant "unit price" as price
participant "units sold" as qty
participant "total revenue" as rev
note over row,rev : All classes below this note are of type <size:20>:PrintColumn<Manga>

ml ++
group sd [Add required columns to list]
    ml -> row ** : add new PrintColumn
    row ++
    return added to columns
    ml -> name ** : add new PrintColumn
    name ++
    return added to columns

    opt deadline flag is set
    ml -> dl ** : add new PrintColumn
    dl ++
    return added to columns
    end

    opt sales data flag set
    ml -> price ** : add new PrintColumn
    price ++
    return added to columns
    ml -> qty ** : add new PrintColumn
    qty ++
    return added to columns
    ml -> rev ** : add new PrintColumn
    rev ++
    return added to columns
    end
end

@enduml