@startuml
actor User
participant "tantou:Tantou" as tantou
participant "ui:Ui" as ui
participant "parser:Parser" as parser
participant "userCommand:AddAuthorCommand" as userCommand
participant "authorList:AuthorList" as authorList
participant ":Storage" as storage
participant "author:Author" as author

' Simulate adding author with "catalog -a Kubo Tite"
activate tantou
User -> ui: "catalog -a Kubo Tite"

' Get userInput
tantou -> ui: getUserInput()
activate ui
ui --> tantou: userInput
deactivate ui

' getUserCommand (AddAuthorCommand)
tantou -> parser: getUserCommand(userInput)
activate parser

' Self call to process userInput
parser -> parser: processCatalogCommand(userInput)

' Parser invokes constructor of AddAuthorCommand
activate parser

' Construction
create userCommand
parser -> userCommand : new AddAuthorCommand(authorName)
activate userCommand
userCommand --> parser: userCommand
deactivate userCommand

' More like a return control situation since it is a self call
parser --> parser
deactivate parser
parser --> tantou: userCommand
deactivate parser

' Execution of command
tantou -> userCommand: execute(ui, authorList)
activate userCommand

' Construction of author
create author
userCommand -> author
activate author
author --> userCommand: author
deactivate author

' Control flow
alt author not in authorList

    userCommand -> authorList: add(author)
    activate authorList
    authorList -> ui: printAddAuthorSuccess(author)
    activate ui
    ui -> User: "Successfully added author: Kubo Tite"
    ui --> authorList
    deactivate ui
    authorList --> userCommand
    deactivate authorList

    userCommand -> storage: saveAuthorListToDataFile(authorList)
    activate storage
    storage --> userCommand
    deactivate storage
    userCommand --> tantou

else author exists in authorList
    userCommand --> tantou: throws TantouException("Author exists!")
    tantou -> ui: showErrorMessage()
    activate ui
    ui --> User: "Author exists!"
    ui --> tantou
    deactivate ui
end
deactivate userCommand
deactivate tantou
@enduml
