@startuml

participant Tantou

participant Parser
participant "userCommand:AddSalesCommand" as userCommand
participant Manga

create userCommand
Parser -> userCommand : new AddSalesCommand(userInput)
activate userCommand
Parser <-- userCommand


userCommand -> userCommand: execute(ui, authorList)
alt Author exists
activate userCommand
    alt Manga exists
        create "salesData:Sale" as Sale
        userCommand -> Sale : new Sale(quantitySold, unitPrice)
        activate Sale
        Sale --> userCommand
        deactivate Sale
        userCommand -> Manga : addSalesData(salesData)
        activate Manga
        Manga --> userCommand :
        deactivate Manga
        userCommand -> userCommand: display success message
        deactivate userCommand
    else Manga does not exist
        userCommand --> Tantou : throws TantouException "Manga does not exist!"
    end
else Author does not exist
    userCommand --> Tantou : throws TantouException "Author does not exist!"
    deactivate userCommand
end

@enduml